const BASE_CASES = [
  ["PT 스튜디오", "pt", "cases_pt.jpg", "피트니스"],
  ["필라테스", "pilates", "cases_pilates.jpg", "피트니스"],
  ["헬스장", "gym", "cases_gym.jpg", "피트니스"],
  ["보험 설계", "insurance", "cases_insurance.jpg", "전문 서비스"],
  ["법률 사무소", "law-firm", "cases_law-firm.jpg", "전문 서비스"],
  ["자동차 디테일링", "car-detailing", "cases_car-detailing.jpg", "자동차"],
  ["차량 렌탈", "car-rental", "cases_car-rental.jpg", "자동차"],
  ["웨딩·스냅", "wedding-snap", "cases_wedding-snap.jpg", "예약 서비스"],
  ["세무 사무소", "tax-office", "cases_tax-office.jpg", "전문 서비스"],
  ["공인중개사", "real-estate", "cases_real-estate.jpg", "부동산"],
  ["카페", "cafe", "cases_cafe.jpg", "매장"],
  ["미용실", "hair-salon", "cases_hair-salon.jpg", "뷰티"],
  ["네일샵", "nail-salon", "cases_nail-salon.jpg", "뷰티"],
  ["기업 홈페이지", "corporate-site", "cases_corporate-site.jpg", "B2B"],
  ["피부관리샵", "skincare", "cases_skincare.jpg", "뷰티"],
  ["왁싱샵", "waxing", "cases_waxing.jpg", "뷰티"],
  ["반영구샵", "semi-permanent", "cases_semi-permanent.jpg", "뷰티"],
  ["반려동물 미용", "pet-grooming", "cases_pet-grooming.jpg", "펫 서비스"],
  ["반려동물 용품", "pet-supplies", "cases_pet-supplies.jpg", "커머스"],
  ["인테리어 업체", "interior", "cases_interior.jpg", "시공"],
  ["이사 업체", "moving", "cases_moving.jpg", "생활 서비스"],
  ["키즈카페", "kids-cafe", "cases_kids-cafe.jpg", "공간 예약"],
  ["스터디카페", "study-cafe", "cases_study-cafe.jpg", "공간 예약"],
  ["영어학원", "english-academy", "cases_english-academy.jpg", "교육"],
  ["수학학원", "math-academy", "cases_math-academy.jpg", "교육"],
  ["입시학원", "exam-academy", "cases_exam-academy.jpg", "교육"],
  ["개인과외", "private-tutoring", "cases_private-tutoring.jpg", "교육"],
  ["청소업체", "cleaning", "cases_cleaning.jpg", "생활 서비스"],
];

const DETAIL_BY_SLUG = {
  pt: ["체험권 신청", "운동 목적별 프로그램 비교", "첫 방문 상담 예약"],
  pilates: ["그룹/개인 레슨 분리", "강사 신뢰도 강조", "시간표 기반 상담 유도"],
  gym: ["시설 투어 신청", "회원권 혜택 정리", "위치 기반 방문 전환"],
  insurance: ["상담 신뢰 확보", "상품군별 문의 분기", "개인정보 입력 부담 완화"],
  "law-firm": ["사건 유형별 진입", "전문성 신뢰 설계", "긴급 상담 CTA 고정"],
  "car-detailing": ["패키지 가격 비교", "전후 이미지 강조", "예약 가능 시간 노출"],
  "car-rental": ["차종별 문의 분기", "장기/단기 렌탈 구분", "모바일 즉시 상담"],
  "wedding-snap": ["포트폴리오 감상 흐름", "촬영 일정 문의", "패키지 구성 비교"],
  "tax-office": ["업무 유형별 문의", "신뢰 지표 강화", "초기 상담 진입 단축"],
  "real-estate": ["매물 상담 전환", "지역 전문성 강조", "전화 CTA 고정"],
  cafe: ["메뉴와 공간 분위기 전달", "단체 예약 문의", "지도/영업시간 강조"],
  "hair-salon": ["시술 메뉴 정리", "디자이너 선택 흐름", "예약 CTA 반복"],
  "nail-salon": ["아트 사례 탐색", "가격대 안내", "카카오 예약 연결"],
  "corporate-site": ["회사 소개 신뢰도", "B2B 문의 폼", "포트폴리오 섹션 강화"],
  skincare: ["관리 프로그램 비교", "전후 케어 설명", "첫 상담 예약"],
  waxing: ["부위별 가격 안내", "위생/프라이버시 강조", "빠른 예약 연결"],
  "semi-permanent": ["시술 안전성 설명", "전후 사례 노출", "상담 예약 전환"],
  "pet-grooming": ["견종별 안내", "예약 전 주의사항", "전화/카카오 연결"],
  "pet-supplies": ["상품 카테고리 탐색", "베스트 상품 강조", "구매 문의 연결"],
  interior: ["시공 사례 탐색", "평형별 상담", "견적 문의 폼"],
  moving: ["이사 유형 선택", "견적 체크리스트", "희망 일정 접수"],
  "kids-cafe": ["공간 이용 안내", "단체 예약", "안전/위생 신뢰"],
  "study-cafe": ["좌석/요금 비교", "지점 위치 안내", "이용권 문의"],
  "english-academy": ["레벨별 과정 안내", "상담 예약", "학부모 신뢰 요소"],
  "math-academy": ["학년별 커리큘럼", "진단 테스트 신청", "성과 사례"],
  "exam-academy": ["입시 전략 상담", "합격 데이터 강조", "설명회 신청"],
  "private-tutoring": ["과목별 상담", "강사 프로필", "무료 테스트 신청"],
  cleaning: ["서비스 범위 선택", "현장 견적 문의", "예약 가능일 안내"],
};

export const CASE_ITEMS = BASE_CASES.map(([title, slug, image, category], index) => {
  const points = DETAIL_BY_SLUG[slug];
  const leadPoint = points[0];
  const conversionRate = 18 + (index % 8) * 4;
  const inquiryCount = 22 + (index % 7) * 9;

  return {
    title,
    slug,
    image,
    category,
    clientType: `${category} 운영팀`,
    projectScope: ["랜딩 구조 설계", "모바일 UI 개선", "상담 CTA 연결"],
    launchPeriod: `${4 + (index % 4)}일 제작`,
    channel: index % 3 === 0 ? "검색 광고 + 카카오 상담" : "모바일 검색 + 전화 상담",
    result: `${leadPoint} 문의 흐름 개선`,
    summary: `${title} 고객이 원하는 정보를 빠르게 확인하고 바로 상담으로 이어질 수 있도록 전환 중심 페이지를 구성했습니다.`,
    description: `${title} 업종의 방문자는 가격, 신뢰, 예약 가능 여부를 짧은 시간 안에 확인하려는 경향이 있습니다. 첫 화면에서 핵심 제안과 상담 버튼을 명확히 보여주고, 중간 섹션에서는 서비스 선택 기준과 실제 이용 흐름을 정리해 이탈 지점을 줄였습니다.`,
    metrics: points,
    kpis: [
      { label: "문의 전환", value: `+${conversionRate}%` },
      { label: "월 상담", value: `${inquiryCount}건` },
      { label: "제작 기간", value: `${4 + (index % 4)}일` },
    ],
    detailCards: [
      { label: "목표", value: `${leadPoint}을 첫 화면에서 바로 이해시키기` },
      { label: "핵심 CTA", value: index % 2 === 0 ? "무료 상담 신청" : "예약 문의하기" },
      { label: "운영 메모", value: "관리자가 문구와 노출 상태를 쉽게 수정할 수 있도록 구성" },
    ],
    timeline: ["진단", "구조 설계", "디자인 정리", "배포"],
    testimonial: `${title}에 맞는 상담 흐름이 생겨 문의 응대가 훨씬 쉬워졌습니다.`,
    visible: true,
  };
});
